version: "2"
linters:
  settings:
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
        - github.com/labstack/echo/v4.Context
        - (go.temporal.io/sdk/internal.Future).Get(
        - .NewNonRetryableApplicationError(

      ignore-package-globs:
        - github.com/satisfactorymodding/smr-api/*

    govet:
      enable:
        - shadow

    gocritic:
      disabled-checks:
        - ifElseChain

    sloglint:
      attr-only: true
      context: scope
      forbidden-keys:
        - time
        - level
        - msg
        - source

    spancheck:
      checks:
        - end
        - record-error

  exclusions:
    paths:
      - ./generated/generated.go
      - ./generated/models_gen.go
      - ./generated/
      - third_party$
      - builtin$
      - examples$
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
        text: 'shadow: declaration of "err" shadows declaration at'
      - path: (.+)\.go$
        text: should pass the context parameter

  default: none

  enable:
    - bidichk
    - canonicalheader
    - contextcheck
    - copyloopvar
    - durationcheck
    - errcheck
    - errorlint
    - fatcontext
    - gocritic
    - govet
    - inamedparam
    - ineffassign
    - intrange
    - misspell
    - nonamedreturns
    - prealloc
    - revive
    - sloglint
    - spancheck
    - staticcheck
    - unused
    - whitespace
    - wrapcheck

formatters:
  enable:
    - gci
    - gofumpt
    - goimports

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/satisfactorymodding/smr-api)
        - blank
        - dot
      custom-order: true

  exclusions:
    generated: lax
    paths:
      - ./generated/generated.go
      - ./generated/models_gen.go
      - ./generated/
      - third_party$
      - builtin$
      - examples$
