linters-settings:
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      - github.com/labstack/echo/v4.Context
      - (go.temporal.io/sdk/internal.Future).Get(
      - .NewNonRetryableApplicationError(

    ignorePackageGlobs:
      - github.com/satisfactorymodding/smr-api/*

  govet:
    disable:
      - shadow

  gocritic:
    disabled-checks:
      - ifElseChain

  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/satisfactorymodding/smr-api)
      - blank
      - dot

  sloglint:
    attr-only: true
    context: scope
    forbidden-keys:
      - time
      - level
      - msg
      - source

  spancheck:
    checks:
      - end
      - record-error


issues:
  exclude-files:
    - ./generated/generated.go
    - ./generated/models_gen.go
  exclude-dirs:
    - ./generated/
  exclude:
    - should pass the context parameter

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bidichk
    - contextcheck
    - durationcheck
    - errorlint
    - goimports
    - revive
    - misspell
    - prealloc
    - whitespace
    - wrapcheck
    - gci
    - gocritic
    - gofumpt
    - nonamedreturns
    - inamedparam
    - sloglint
    - spancheck
    - intrange
    - copyloopvar
    - fatcontext
    - canonicalheader
