linters-settings:
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      - github.com/labstack/echo/v4.Context

    ignorePackageGlobs:
      - github.com/satisfactorymodding/smr-api/*

  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - shadow

  gocritic:
    disabled-checks:
      - ifElseChain

  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/satisfactorymodding/smr-api)
      - blank
      - dot

run:
  skip-files:
    - ./generated/generated.go
    - ./generated/models_gen.go
  skip-dirs:
    - ./generated/

issues:
  exclude:
    - should pass the context parameter

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bidichk
    - contextcheck
    - durationcheck
    - errorlint
    - goimports
    - revive
    - misspell
    - prealloc
    - whitespace
    - wrapcheck
    - gci
    - gocritic
    - gofumpt
    - nonamedreturns
