version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "1-bullseye"
        NODE_VERSION: "none"
    volumes:
      - ..:/workspace:cached
    cap_add:
      - SYS_PTRACE
    network_mode: service:postgres

  redis:
    image: redis:alpine
    network_mode: service:postgres

  postgres:
    image: postgres:alpine
    command: postgres -N 500 -B 4096MB
    environment:
      POSTGRES_PASSWORD: REPLACE_ME
    ports:
      - 5432:5432
      - 6379:6379
      - 9000:9000
      - 9001:9001
      - 5020:5020
  
  minio:
    image: minio/minio
    network_mode: service:postgres
    entrypoint: sh
    command: -c 'mkdir -p /data/smr && /usr/bin/docker-entrypoint.sh minio server /data --console-address ":9001"'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_ACCESS_KEY: REPLACE_ME_KEY
      MINIO_SECRET_KEY: REPLACE_ME_SECRET
