// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: parser/parser.proto

package parser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZipData       []byte                 `protobuf:"bytes,1,opt,name=zip_data,json=zipData,proto3" json:"zip_data,omitempty"`
	EngineVersion string                 `protobuf:"bytes,2,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_parser_parser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parser_parser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_parser_parser_proto_rawDescGZIP(), []int{0}
}

func (x *ParseRequest) GetZipData() []byte {
	if x != nil {
		return x.ZipData
	}
	return nil
}

func (x *ParseRequest) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

type AssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetResponse) Reset() {
	*x = AssetResponse{}
	mi := &file_parser_parser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetResponse) ProtoMessage() {}

func (x *AssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parser_parser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetResponse.ProtoReflect.Descriptor instead.
func (*AssetResponse) Descriptor() ([]byte, []int) {
	return file_parser_parser_proto_rawDescGZIP(), []int{1}
}

func (x *AssetResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AssetResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_parser_parser_proto protoreflect.FileDescriptor

const file_parser_parser_proto_rawDesc = "" +
	"\n" +
	"\x13parser/parser.proto\"P\n" +
	"\fParseRequest\x12\x19\n" +
	"\bzip_data\x18\x01 \x01(\fR\azipData\x12%\n" +
	"\x0eengine_version\x18\x02 \x01(\tR\rengineVersion\"7\n" +
	"\rAssetResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data22\n" +
	"\x06Parser\x12(\n" +
	"\x05Parse\x12\r.ParseRequest\x1a\x0e.AssetResponse0\x01B5Z3github.com/satisfactorymodding/smr-api/proto/parserb\x06proto3"

var (
	file_parser_parser_proto_rawDescOnce sync.Once
	file_parser_parser_proto_rawDescData []byte
)

func file_parser_parser_proto_rawDescGZIP() []byte {
	file_parser_parser_proto_rawDescOnce.Do(func() {
		file_parser_parser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_parser_parser_proto_rawDesc), len(file_parser_parser_proto_rawDesc)))
	})
	return file_parser_parser_proto_rawDescData
}

var file_parser_parser_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_parser_parser_proto_goTypes = []any{
	(*ParseRequest)(nil),  // 0: ParseRequest
	(*AssetResponse)(nil), // 1: AssetResponse
}
var file_parser_parser_proto_depIdxs = []int32{
	0, // 0: Parser.Parse:input_type -> ParseRequest
	1, // 1: Parser.Parse:output_type -> AssetResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_parser_parser_proto_init() }
func file_parser_parser_proto_init() {
	if File_parser_parser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_parser_parser_proto_rawDesc), len(file_parser_parser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_parser_parser_proto_goTypes,
		DependencyIndexes: file_parser_parser_proto_depIdxs,
		MessageInfos:      file_parser_parser_proto_msgTypes,
	}.Build()
	File_parser_parser_proto = out.File
	file_parser_parser_proto_goTypes = nil
	file_parser_parser_proto_depIdxs = nil
}
