version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 1-bullseye
    volumes:
      - ..:/workspace:cached

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  postgres:
    image: postgres:alpine
    command: postgres -N 500 -B 4096MB
    environment:
      POSTGRES_PASSWORD: REPLACE_ME
    ports:
      - 5432:5432

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    entrypoint: sh
    command: -c 'mkdir -p /data/smr && /usr/bin/docker-entrypoint.sh minio server /data --console-address ":9001"'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_ACCESS_KEY: REPLACE_ME_KEY
      MINIO_SECRET_KEY: REPLACE_ME_SECRET
