enum CompatibilityState {
    Works
    Damaged
    Broken
}

type Compatibility {
    state: CompatibilityState!
    note: String
}

input CompatibilityInput {
    state: CompatibilityState!
    note: String
}

enum ControllerCompatibilityState {
    Untested
    Unsupported
    Partial
    Implicit
    Supported
}

type ControllerCompatibility {
    state: ControllerCompatibilityState!
    note: String
}

input ControllerCompatibilityInput {
    state: ControllerCompatibilityState!
    note: String
}

type CompatibilityInfo {
    EA: Compatibility!
    EXP: Compatibility!
    Controller: ControllerCompatibility!
}

input CompatibilityInfoInput {
    EA: CompatibilityInput!
    EXP: CompatibilityInput!
    Controller: ControllerCompatibilityInput!
}

extend type Mutation {
    updateModCompatibility(modId: ModID!, compatibility: CompatibilityInfoInput!): Boolean! @canEditModCompatibility(field: "modId") @isLoggedIn
    updateMultipleModCompatibilities(modIDs: [ModID!]!, compatibility: CompatibilityInfoInput!): Boolean! @canEditModCompatibility @isLoggedIn
}
