name: generated

on:
  - push
  - pull_request

jobs:
  atlas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: Hash migrations
        run: mise run migrate_hash

      - name: Make sure all changes generated
        run: echo 'ci_migration' | mise run migrate_diff

      - name: Tidy
        run: go mod tidy

      - name: Ensure no changes
        run: git diff --exit-code

  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: Run generation tasks
        run: mise run generate

      - name: Tidy
        run: go mod tidy

      - name: Ensure no changes
        run: git diff --exit-code
